apiVersion: skaffold/v2beta14
kind: Config
metadata:
  name: optichub
build:
  artifacts:
    - image: 513974440343.dkr.ecr.us-east-1.amazonaws.com/docs
      docker:
        dockerfile: Dockerfile
deploy:
  helm:
    releases:
      - name: optichub
        chartPath: chart/
        valuesFiles:
          - values.development.yaml
        artifactOverrides:
          image: 513974440343.dkr.ecr.us-east-1.amazonaws.com/docs
profiles:
  - name: staging
    activation:
      - kubeContext: staging
    patches:
      - op: replace
        path: /deploy/helm/releases/0/valuesFiles/0
        value: values.staging.yaml
  - name: production
    activation:
      - kubeContext: production
    patches:
      - op: replace
        path: /deploy/helm/releases/0/valuesFiles/0
        value: values.production.yaml
