apiVersion: skaffold/v2beta14
kind: Config
metadata:
  name: docs
build:
  artifacts:
    - image: 513974440343.dkr.ecr.us-east-1.amazonaws.com/docs
      docker:
        dockerfile: Dockerfile
deploy:
  helm:
    releases:
      - name: docs
        namespace: docs
        createNamespace: true
        chartPath: k8s/
        valuesFiles:
          - k8s/values.development.yaml
        artifactOverrides:
          image: 513974440343.dkr.ecr.us-east-1.amazonaws.com/docs
profiles:
  - name: staging
    activation:
      - kubeContext: staging
    patches:
      - op: replace
        path: /deploy/helm/releases/0/valuesFiles/0
        value: k8s/values.staging.yaml
  - name: production
    activation:
      - kubeContext: production
    patches:
      - op: replace
        path: /deploy/helm/releases/0/valuesFiles/0
        value: k8s/values.production.yaml
